'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Texts
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DoenaSoft.STC.Texts", GetType(Texts).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to c.
        '''</summary>
        Friend Shared ReadOnly Property c() As String
            Get
                Return ResourceManager.GetString("c", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered date is invalid..
        '''</summary>
        Friend Shared ReadOnly Property DateIsInvalid() As String
            Get
                Return ResourceManager.GetString("DateIsInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;{0}&apos; ist ungültig, bitte geben sie einen Wert zwischen {1} und {2} ein..
        '''</summary>
        Friend Shared ReadOnly Property DatePartIsInvalid() As String
            Get
                Return ResourceManager.GetString("DatePartIsInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day.
        '''</summary>
        Friend Shared ReadOnly Property Day() As String
            Get
                Return ResourceManager.GetString("Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distance.
        '''</summary>
        Friend Shared ReadOnly Property Distance() As String
            Get
                Return ResourceManager.GetString("Distance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you enter a distance (in light years)
        '''and chosse one of the two calculation options,
        '''the travelling time will be calculated based on the entered speed
        '''and distance..
        '''</summary>
        Friend Shared ReadOnly Property DistanceTooltip() As String
            Get
                Return ResourceManager.GetString("DistanceTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hour.
        '''</summary>
        Friend Shared ReadOnly Property Hour() As String
            Get
                Return ResourceManager.GetString("Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minute.
        '''</summary>
        Friend Shared ReadOnly Property Minute() As String
            Get
                Return ResourceManager.GetString("Minute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month.
        '''</summary>
        Friend Shared ReadOnly Property Month() As String
            Get
                Return ResourceManager.GetString("Month", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Second.
        '''</summary>
        Friend Shared ReadOnly Property Second() As String
            Get
                Return ResourceManager.GetString("Second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stardate.
        '''</summary>
        Friend Shared ReadOnly Property Stardate() As String
            Get
                Return ResourceManager.GetString("Stardate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unexpected error has occured..
        '''</summary>
        Friend Shared ReadOnly Property UnexpectedError() As String
            Get
                Return ResourceManager.GetString("UnexpectedError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid &apos;{0}&apos; value. Please enter a value between {1} and {2}..
        '''</summary>
        Friend Shared ReadOnly Property ValueIsInvalid() As String
            Get
                Return ResourceManager.GetString("ValueIsInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warp.
        '''</summary>
        Friend Shared ReadOnly Property Warp() As String
            Get
                Return ResourceManager.GetString("Warp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend Shared ReadOnly Property Year() As String
            Get
                Return ResourceManager.GetString("Year", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
